name: ashfold
logger:
  level: "INFO"
console:
  max_message_size_bytes: 409600
session:
  token_expiry_sec: 7200
  refresh_token_expiry_sec: 2592000
socket:
  max_message_size_bytes: 131072
  max_request_size_bytes: 131072
runtime:
  path: "/nakama/data/modules"
  http_key: "defaulthttpkey"
